# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

#@TYPE: Machine
#@NAME: seapath-vm-arm64
#@SOC: ARM64
#@DESCRIPTION: Machine configuration for virtual machines compatible with SEAPATH for ARM64 architecture

require conf/machine/seapath-machine-common-qcom.inc
require conf/machine/include/arm/arch-armv8-2a.inc

PREFERRED_PROVIDER_virtual/kernel = "linux-mainline-rt"
PREFERRED_VERSION_linux-mainline-rt ?= "6.12.%"
IMAGE_FSTYPES = "wic"

MACHINE_FEATURES:append = "seapath-guest"

# We only need the serial console on VM
APPEND:remove = "console=tty0"

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "grub-efi"
