# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "meta-seapath-qcom"
BBFILE_PATTERN_meta-seapath-qcom = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-seapath-qcom = "21"

LAYERSERIES_COMPAT_meta-seapath-qcom = "wrynose"

# Mask bbappend for recipes that SEAPATH doesn't use
BBMASK += "\
  meta-qcom-hwe/recipes-multimedia \
  meta-qcom-hwe/recipes-extended/libcamera \
  meta-seapath/recipes-bsp/bootfiles/rpi-cmdline.bbappend \
  meta-seapath/recipes-kernel/linux/linux-raspberrypi_%.bbappend \
  meta-qcom-hwe/recipes-firmware/firmware/linux-firmware_%.bbappend \
  "
