# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

require conf/distro/seapath-host.conf

# Add dmaheap gid for useradd-qcom required for QCOM BSP
USERADD_GID_TABLES:append = " conf/distro/include/group-qcom.gid"

# Disable hardening because linux-qcom doesn't copy its configuration
# where the hardening analysis wants it
DISTRO_FEATURES:remove = 'seapath-security'

DISTRO_FEATURES:remove = 'seapath-clustering'
DISTRO_FEATURES:remove = 'seapath-readonly'

QEMU_TARGETS:pn-qemu:append = " aarch64"

IMAGE_CLASSES:append = " image_types_qcom"
